(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"2004030010070",f:(function(AMP,_){
var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ka=b.prototype}
function ia(a){for(var b=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return function(){throw Error("Cannot find global object");}()}var ja=ia(this);function ka(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ma="";
function u(){var a,b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=q(c.location.originalHash||c.location.hash);d=d.spt;var g=q(c.location.search);ma||(ma=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"012004030010070");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(f.development)||c.AMP_DEV_MODE),examiner:"2"==f.development,esm:!1,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,version:"2004030010070",
rtvVersion:ma,singlePassType:d};c=b.__AMP_MODE=c}return c};var na=Object.prototype.toString;function v(a){return a?Array.prototype.slice.call(a):[]}function w(a){return"[object Object]"===na.call(a)};var x=self.AMP_CONFIG||{},y={thirdParty:x.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:x.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof x.thirdPartyFrameRegex?new RegExp(x.thirdPartyFrameRegex):x.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:x.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof x.cdnProxyRegex?new RegExp(x.cdnProxyRegex):x.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:x.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:x.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:x.geoApiUrl};function oa(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var z=self.__AMP_LOG;function A(){if(!z.user)throw Error("failed to call initLogConstructor");return z.user}function B(){if(z.dev)return z.dev;throw Error("failed to call initLogConstructor");}
function C(a,b,c,d,e){return A().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var D=Object.prototype.hasOwnProperty;function E(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function F(a){return a||{}}function I(a,b){if(D.call(a,b))return a[b]}
function pa(a,b){var c=10;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.F=b.t;a.B=b.s;a.N=b.d;if(d.includes(a.B))throw Error("Source object has a circular reference.");d.push(a.B);a.F!==a.B&&(a.N>c?Object.assign(a.F,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(D.call(a.F,b)){var d=a.F[b];if(w(c)&&w(d)){e.push({t:d,s:c,d:a.N+1});return}}a.F[b]=c}}(a)));a={B:a.B,F:a.F,N:a.N}}};function J(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var qa,ra="Webkit webkit Moz moz ms O o".split(" ");function sa(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function ta(){return AMP.BaseElement.apply(this,arguments)||this}ha(ta,AMP.BaseElement);l=ta.prototype;l.getLayoutPriority=function(){return 1};l.isAlwaysFixed=function(){return!0};l.isLayoutSupported=function(){return!0};l.renderOutsideViewport=function(){return!0};l.P=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};function K(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function ua(){var a=100;this.va=a;this.W=this.aa=0;this.O=Object.create(null)}ua.prototype.has=function(a){return!!this.O[a]};ua.prototype.get=function(a){var b=this.O[a];if(b)return b.access=++this.W,b.payload};ua.prototype.put=function(a,b){this.has(a)||this.aa++;this.O[a]={payload:b,access:this.W};if(!(this.aa<=this.va)){B().warn("lru-cache","Trimming LRU cache");a=this.O;var c=this.W+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.aa--)}};var va=F({c:!0,v:!0,a:!0,ad:!0,action:!0}),wa,xa,ya=/[?&]amp_js[^&]*/,za=/[?&]amp_gsa[^&]*/,Aa=/[?&]amp_r[^&]*/,Ba=/[?&]amp_kit[^&]*/,Ca=/[?&]usqp[^&]*/;
function L(a){var b;wa||(wa=self.document.createElement("a"),xa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new ua));var c=b?null:xa,d=wa;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=
e.hostname;e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}
function Da(a,b){var c=void 0===c?"source":c;C(null!=a,"%s %s must be available",b,c);var d=a;a=d;"string"==typeof a&&(a=L(a));var e;(e="https:"==a.protocol||"localhost"==a.hostname||"127.0.0.1"==a.hostname)||(a=a.hostname,e=a.length-10,e=0<=e&&a.indexOf(".localhost",e)==e);C(e||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}
function M(a){"string"==typeof a&&(a=L(a));return y.cdnProxyRegex.test(a.origin)}
function Ea(a){"string"==typeof a&&(a=L(a));if(!M(a))return a.href;var b=a.pathname.split("/");C(va[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);C(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(ya,"").replace(za,"").replace(Aa,"").replace(Ba,"").replace(Ca,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function Fa(a,b){"string"==typeof b&&(b=L(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=L(d));c=c.replace(/\\/g,"/");var e=L(c);c=J(c.toLowerCase(),e.protocol)?e.href:J(c,"//")?d.protocol+c:J(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Ga(a){var b=L(a),c=q(b.search);C(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function Ja(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,Ka(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=q(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}var g=c;return!!g[b]}
function Ka(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){B().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};var La={},N=(La["ampdoc-fie"]={isTrafficEligible:function(){return!0},branches:[["21065001"],["21065002"]]},La);
function Ma(a){if(!Ja(a,"ampdoc-fie"))return!1;a.__AMP_EXPERIMENT_BRANCHES=a.__AMP_EXPERIMENT_BRANCHES||{};for(var b in N)if(D.call(N,b)&&!D.call(a.__AMP_EXPERIMENT_BRANCHES,b))if(!N[b].isTrafficEligible||!N[b].isTrafficEligible(a))a.__AMP_EXPERIMENT_BRANCHES[b]=null;else if(!a.__AMP_EXPERIMENT_BRANCHES[b]&&Ja(a,b)){var c=N[b].branches;a.__AMP_EXPERIMENT_BRANCHES[b]=c[Math.floor(Math.random()*c.length)]||null}return"21065002"===(a.__AMP_EXPERIMENT_BRANCHES?a.__AMP_EXPERIMENT_BRANCHES["ampdoc-fie"]:
null)};function Na(a,b){var c=a.ownerDocument.defaultView,d=O(c),e=c!=d,f=Ma(d);e&&!f?b=Oa(c,b)?P(c,b):null:(a=Q(a),a=R(a),b=Oa(a,b)?P(a,b):null);return b}function Pa(a,b){var c=O(a);Oa(a,"bind");if(Ma(c)){var d=Q(a.document);Qa(R(d),d,"bind",function(){return b},!0)}else Qa(a,a,"bind",function(){return b}),P(a,"bind")}function S(a,b){a=O(a);return P(a,b)}function T(a,b){var c=Q(a);c=R(c);return P(c,b)}function Ra(a,b){return Sa(R(a),b)}function O(a){return a.__AMP_TOP||(a.__AMP_TOP=a)}
function Q(a){return a.nodeType?S((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function R(a){a=Q(a);return a.isSingleDoc()?a.win:a}function P(a,b){Oa(a,b);var c=Ta(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Qa(a,b,c,d,e){var f=Ta(a),g=f[c];g||(g=f[c]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});if(e||!g.ctor&&!g.obj)g.ctor=d,g.context=b,g.resolve&&P(a,c)}
function Ua(a,b){var c=Sa(a,b);if(c)return c;a=Ta(a);a[b]=Va();return a[b].promise}function Sa(a,b){var c=Ta(a)[b];if(c){if(c.promise)return c.promise;P(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Ta(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function Oa(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function Va(){var a=new K,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Wa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Xa(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function Ya(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function Za(a,b){Ya(a.documentElement,function(){return!!a.body},b)}function $a(a){return new Promise(function(b){return Za(a,b)})}function ab(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}
function bb(a,b){return a.closest?a.closest(b):ab(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}function cb(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function db(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()}
function eb(a){J(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new K;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function fb(a,b,c){var d=Ra(a,b);if(d)return d;var e=Q(a);return e.waitForBodyOpen().then(function(){return gb(e.win,c,e.win.document.head)}).then(function(){var d=e.win;return d.__AMP_EXTENDED_ELEMENTS&&d.__AMP_EXTENDED_ELEMENTS[c]?Ua(R(a),b):null})}function ib(a){var b=Na(a,"bind");if(b)return Promise.resolve(b);b=a.ownerDocument.defaultView;var c=O(b);return b!==c?jb(b):fb(a,"bind","amp-bind")}
function gb(a,b,c){if(c){var d={};c=c.querySelectorAll("script[custom-element],script[custom-template]");for(var e=0;e<c.length;e++){var f=c[e];f=f.getAttribute("custom-element")||f.getAttribute("custom-template");d[f]=!0}d=Object.keys(d)}else d=[];if(!d.includes(b))return Promise.resolve();var g=S(a,"extensions");return g.waitForExtension(a,b)}
function jb(a){return $a(a.document).then(function(){return gb(a,"amp-bind",a.document.head)}).then(function(){return a.__AMP_EXTENDED_ELEMENTS&&a.__AMP_EXTENDED_ELEMENTS["amp-bind"]?Ua(a,"bind"):null})};function kb(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function lb(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}}
function mb(a,b){var c=20;c=void 0===c?5:c;if(!isFinite(c)||0>c)throw Error("Invalid depth: "+c);if(a===b)return!0;for(a=[{a:a,b:b,depth:c}];0<a.length;){var d=a.shift();b=d.a;c=d.b;d=d.depth;if(0<d){if(typeof b!==typeof c)return!1;if(Array.isArray(b)&&Array.isArray(c)){if(b.length!==c.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:c[e],depth:d-1});continue}else if(b&&c&&"object"===typeof b&&"object"===typeof c){var f=Object.keys(b),g=Object.keys(c);if(f.length!==g.length)return!1;for(e=
0;e<f.length;e++){var k=f[e];a.push({a:b[k],b:c[k],depth:d-1})}continue}}if(b!==c)return!1}return!0};function nb(a,b,c){c=void 0===c?{}:c;var d=void 0===c.expr?".":c.expr,e=void 0===c.urlReplacement?0:c.urlReplacement,f=void 0===c.refresh?!1:c.refresh,g=void 0===c.token?void 0:c.token,k=void 0===c.xssiPrefix?void 0:c.xssiPrefix;Da(b.getAttribute("src"),b);var h=S(a.win,"batched-xhr");return ob(b,e,f).then(function(a){void 0!==g&&(a.fetchOpt.method="POST",a.fetchOpt.headers={"Content-Type":"application/x-www-form-urlencoded"},a.fetchOpt.body={ampViewerAuthToken:g});return h.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(b){return S(a.win,
"xhr").xssiJson(b,k)}).then(function(a){if(null==a)throw Error("Response is undefined.");return kb(a,d||".")}).catch(function(a){throw A().createError("failed fetching JSON data",a);})}
function ob(a,b,c){var d=a.getAttribute("src"),e=Na(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(d){if(1==b){var f=e.collectUnwhitelistedVarsSync(a);if(0<f.length)throw A().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(f.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var k={};a.hasAttribute("credentials")&&(k.credentials=a.getAttribute("credentials"));
c&&(k.cache="reload");return{xhrUrl:d,fetchOpt:k}})};function pb(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function qb(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)}function rb(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function sb(a){var b=a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?fb(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){C(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}).then(function(a){return a||""}).catch(function(){return""}):Promise.resolve(void 0)};function xb(a){a=AMP.BaseElement.call(this,a)||this;a.R=void 0;a.$=new K;return a}ha(xb,AMP.BaseElement);l=xb.prototype;l.getLayoutPriority=function(){return 1};l.isAlwaysFixed=function(){return!0};l.isLayoutSupported=function(){return!0};
l.buildCallback=function(){var a=this;sa(this.element);this.element.setAttribute("aria-hidden","true");var b=this.element;b.hasAttribute("overridable")&&ib(b).then(function(a){a.addOverridableKey(b.getAttribute("id"))});this.parseAndUpdate();this.element.hasAttribute("src")&&yb(this,!0);this.registerAction("refresh",function(){C(a.element.hasAttribute("src"),'Can\'t refresh <amp-state> without "src" attribute.');yb(a,!1,!0)})};
l.mutatedAttributesCallback=function(a){if(this.getAmpDoc().hasBeenVisible())void 0!==a.src&&this.element.hasAttribute("src")&&yb(this,!1);else{var b=this.P();B().error(b,"ampdoc must be visible before mutation.")}};l.renderOutsideViewport=function(){return!0};l.parseAndUpdate=function(){return void 0===this.R&&(this.R=zb(this),null!==this.R)?Ab(this,this.R,!0):Promise.resolve()};
function zb(a){var b=a.element.children;if(0==b.length)return null;var c=a.P();if(1!=b.length)return a.user().error(c,"Should contain exactly one <script> child."),null;var d=b[0];return db(d)?lb(d.textContent,function(b){a.user().error(c,"Failed to parse state. Is it valid JSON?",b)}):(a.user().error(c,'State should be in a <script> tag with type="application/json".'),null)}
function Bb(a,b,c){var d=a.element,e=a.getAmpDoc(),f=d.getAttribute("src"),g=L(Ea(f)).origin!==L(Ea(e.win.location)).origin,k=g&&!b?1:2;return sb(d).then(function(b){return nb(e,a.element,{urlReplacement:k,refresh:c,token:b}).catch(function(b){b=b?pb(a.win,"amp-state.error",F({response:b.response})):null;var c=Na(d,"action");c.trigger(d,"fetch-error",b,1)})})}
function yb(a,b,c){b||(a.$=new K);var d=a.$;a.getAmpDoc().whenFirstVisible().then(function(){return Bb(a,b,c)}).then(function(c){return Ab(a,c,b)}).then(function(){return d.resolve()}).catch(function(a){d.resolve();throw a;})}l.getFetchingPromise=function(){return this.element.hasAttribute("src")?this.$.promise:Promise.resolve()};
function Ab(a,b,c){if(void 0===b||null===b)return Promise.resolve();var d=C(a.element.id,"<amp-state> must have an id.");return ib(a.element).then(function(a){var e=E();e[d]=b;a.setState(e,{skipEval:c,skipAmpState:!c})})}l.P=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var Cb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function Db(a){for(var b=[],c;c=Cb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new Eb(b)}
function Eb(a){C(0<a.length,"Srcset must have at least one source");this.M=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}C(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?Fb:Gb);this.ra=b}
Eb.prototype.select=function(a,b){if(this.ra){b*=a;a=this.M;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,k=Math.abs(g-b);if(k<=1.1*d||1.2<b/e)c=f,d=k,e=g;else break}b=c}else{a=this.M;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.M[b].url};Eb.prototype.getUrls=function(){return this.M.map(function(a){return a.url})};
Eb.prototype.stringify=function(a){for(var b=[],c=this.M,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.ra?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function Fb(a,b){C(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function Gb(a,b){C(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var Hb={"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},Ib={width:null,height:null},Jb={"AMP-AUDIO":{album:null,artist:null,artwork:null,controlsList:null,loop:null,src:{allowedProtocols:{https:!0}},title:null},"AMP-AUTOCOMPLETE":{src:{allowedProtocols:{https:!0}}},"AMP-BASE-CAROUSEL":{"advance-count":null,"auto-advance-count":null,"auto-advance-interval":null,"auto-advance-loops":null,"auto-advance":null,horizontal:null,"initial-index":null,loop:null,"mixed-length":null,
"side-slide-count":null,slide:null,"snap-align":null,"snap-by":null,snap:null,"visible-count":null},"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null,title:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,
https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-TWITTER":{"data-tweetid":null},"AMP-VIDEO":{album:null,alt:null,artist:null,artwork:null,attribution:null,controls:null,controlslist:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}},
title:null},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,geo:!0,http:!0,https:!0,mailto:!0,maps:!0,bip:!0,bbmi:!0,chrome:!0,"itms-services":!0,facetime:!0,"fb-me":!0,"fb-messenger":!0,intent:!0,line:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,webcal:!0,"web+mastodon":!0,wh:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,
accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SECTION:{"data-expand":null},SELECT:{autofocus:null,disabled:null,
multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,pattern:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null,defaulttext:null}},Kb={src:!0,srcset:!0,href:!0,"xlink:href":!0};
function Lb(a){this.ta=a}Lb.prototype.canBind=function(a,b){return void 0!==Mb(this,a,b)};
Lb.prototype.isResultValid=function(a,b,c){var d=Mb(this,a,b);d&&d.alternativeName&&(d=Mb(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&I(Kb,b)){if("srcset"===b){try{var e=Db(c)}catch(n){return A().error("amp-bind","Failed to parse srcset: ",n),!1}var f=e.getUrls()}else f=[c];for(a=0;a<f.length;a++){a:{var g=f[a];b=d;if(g){if(/__amp_source_origin/.test(g)){b=!1;break a}if(b=b.allowedProtocols)if(g=/^([^:\/?#.]+):[\s\S]*$/.exec(g),null!==g&&(g=g[1].toLowerCase().trim(),
!D.call(b,g))){b=!1;break a}}b=!0}if(!b)return!1}}var k=d.blacklistedValueRegex;if(c&&k){var h=new RegExp(k,"i");if(h.test(c))return!1}return!0};function Mb(a,b,c){if(J(c,"aria-"))return null;if(!I(Kb,c)||a.ta){var d=I(Hb,c);if(void 0!==d)return d;var e=I(Ib,c);if(J(b,"AMP-")&&void 0!==e)return e;var f=I(Jb,b);if(f)return f[c]}};var Nb=!1;function Ob(a){if(!Nb){Nb=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var f=d.style;var g=c;if(J(g,"--"))f=g;else{qa||(qa=E());var k=qa[g];if(!k){k=g;if(void 0===f[g]){var h=g;h=h.charAt(0).toUpperCase()+h.slice(1);b:{for(var n=0;n<ra.length;n++){var m=ra[n]+h;if(void 0!==f[m]){h=m;break b}}h=""}void 0!==f[h]&&(k=h)}qa[g]=k}f=k}f&&(J(f,"--")?d.style.setProperty(f,e):d.style[f]=e)}}};function U(){this.o=[]}U.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};U.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=b,d=-1,e=0,f=this.o.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.o.length)break;if(this.o[d].priority<c)e=d+1;else if(0<d&&this.o[d-1].priority>=c)f=d-1;else break}this.o.splice(d,0,{item:a,priority:b})};U.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
U.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};ja.Object.defineProperties(U.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var Pb=/nochunking=1/.test(self.location.hash),Qb=Promise.resolve();function Rb(a,b){if(Pb)Qb.then(b);else{var c=Sb,d=Q(a),e=R(d);Qa(e,d,"chunk",c);T(a,"chunk").run(b,10)}}function V(a){this.state="not_run";this.Y=a}function Tb(a,b){if("run"!=a.state){a.state="run";try{a.Y(b)}catch(c){throw a.la(),c;}}}V.prototype.P=function(){return this.Y.displayName||this.Y.name};V.prototype.la=function(){};V.prototype.ja=function(){return!1};V.prototype.pa=function(){return!1};
function W(a,b,c){V.call(this,a);this.fa=c}ha(W,V);W.prototype.la=function(){Ob(self.document)};W.prototype.ja=function(){return this.fa.ampdoc.isVisible()};W.prototype.pa=function(){return this.fa.ga};
function Sb(a){var b=this;this.ampdoc=a;this.h=a.win;this.J=new U;this.ea=this.ha.bind(this);this.K=0;this.T=!1;this.ua=this.h.document.documentElement.hasAttribute("i-amphtml-no-boilerplate");this.h.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.ha(null)});this.ga=!1;Ua(R(a),"viewer").then(function(){b.ga=!0});a.onVisibilityChanged(function(){a.isVisible()&&Ub(b)})}Sb.prototype.run=function(a,b){var c=new V(a);this.J.enqueue(c,b);Ub(this)};
Sb.prototype.runForStartup=function(a){a=new W(a,this.h,this);this.J.enqueue(a,Number.POSITIVE_INFINITY);Ub(this)};function Vb(a,b){for(var c=a.J.peek();c&&"not_run"!==c.state;)a.J.dequeue(),c=a.J.peek();c&&b&&a.J.dequeue();return c}Sb.prototype.ha=function(a){var b=this,c=Vb(this,!0);if(!c)return this.T=!1,this.K=0,!1;try{var d=Date.now();Tb(c,a)}finally{Qb.then().then().then().then().then().then().then().then().then(function(){b.T=!1;b.K+=Date.now()-d;Ub(b)})}return!0};
function Wb(a){a.ua&&5<a.K?(a.K=0,Xb(a)):Qb.then(function(){a.ea(null)})}function Ub(a){if(!a.T){var b=Vb(a);b&&(b.ja()?(a.T=!0,Wb(a)):b.pa()&&a.h.requestIdleCallback?Yb(a.h,a.ea):Xb(a))}}function Xb(a){a.h.postMessage("amp-macro-task","*")}function Yb(a,b){function c(f){if(f.timeRemaining()<d){var g=2E3-(Date.now()-e);0>=g||f.didTimeout?b(f):a.requestIdleCallback(c,{timeout:g})}else b(f)}var d=15,e=Date.now();a.requestIdleCallback(c,{timeout:2E3})};function Zb(){this.D=E();this.j=null}l=Zb.prototype;l.get=function(a){a=this.D[a];return null==a?null:a};l.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.D[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new K,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=E());this.j[a]=b}return b.promise};
l.signal=function(a,b){if(null==this.D[a]){var c=b||Date.now();this.D[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};l.rejectSignal=function(a,b){null==this.D[a]&&(this.D[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.resolve=void 0,a.reject=void 0))};l.reset=function(a){this.D[a]&&delete this.D[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function $b(a,b){function c(){d=0;var g=5E3-(a.Date.now()-e);if(0<g)d=a.setTimeout(c,g);else{var k=f;f=null;b.apply(null,k)}}var d=0,e=0,f=null;return function(b){for(var g=[],h=0;h<arguments.length;++h)g[h-0]=arguments[h];e=a.Date.now();f=g;d||(d=a.setTimeout(c,5E3))}};function ac(a,b,c){var d="ww",e=u().esm?".mjs":".js";if(b){var f=a.protocol+"//"+a.host;"about:"==a.protocol&&(f="");a=f+"/dist"}else a=y.cdn;return b?a+"/"+d+e:c?a+"/rtv/"+u().rtvVersion+"/"+d+e:a+"/"+d+e};function bc(a){var b=this;this.h=a;this.Ea=S(a,"xhr");var c=a.location,d=!1,e=!d,f=ac(c,d,e);this.ba=null;this.ia=this.Ea.fetchText(f,{ampCors:!1,bypassInterceptorForDev:!1}).then(function(a){return a.text()}).then(function(c){c=new a.Blob([c+"\n//# sourceurl="+f],{type:"text/javascript"});var d=a.URL.createObjectURL(c);b.ba=new a.Worker(d);b.ba.onmessage=b.Ca.bind(b)});this.S={};this.wa=0;this.sa=[a]}
function cc(a,b,c,d){return a.ia.then(function(){return new Promise(function(e,f){var g=a.wa++;a.S[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.sa.indexOf(e);var k=0<=f?f:a.sa.push(e)-1;a.ba.postMessage({method:b,args:c,scope:k,id:g})})})}bc.prototype.Ca=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.S[b];d?(d.resolve(c),delete this.S[b]):B().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
bc.prototype.hasPendingMessages=function(){return 0<Object.keys(this.S).length};bc.prototype.Fa=function(){return this.ia};function dc(a){var b=["\u26a14email","amp4email"],c=a.documentElement,d=b.some(function(a){return c.hasAttribute(a)});return d};function ec(){var a=1.5,b=fc(a);return function(a){return setTimeout(a,b())}}function fc(a){var b=a||2,c=0;return function(){var a=Math.pow(b,c++);var e=a*(e||.3)*Math.random();.5<Math.random()&&(e*=-1);a+=e;return 1E3*a}};var X=self.__AMP_ERRORS||[];self.__AMP_ERRORS=X;function gc(a){gc=ec();return gc(a)}function hc(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var ic;
function Y(a,b){try{if(a)if(void 0!==a.message)a=oa(a);else{var c=a;a=Error(hc(c));a.origError=c}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),u().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?e.call(console,a.message,d):e.call(console,a.message)}d&&d.za&&
d.za("amp:error",a.message);jc.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(f){setTimeout(function(){throw f;})}}function jc(a,b,c,d,e){var f=this;this&&this.document&&Ob(this.document);if(!u().development){var g=!1;try{g=kc()}catch(h){}if(!(g&&.01<Math.random())){var k=lc(a,b,c,d,e,g);k&&gc(function(){try{return mc(f,k).catch(function(){})}catch(h){}})}}}
function mc(a,b){return nc(a,b).then(function(a){if(!a){var c=new XMLHttpRequest;c.open("POST",y.errorReporting,!0);c.send(JSON.stringify(b))}})}
function nc(a,b){var c=S(a,"ampdoc");if(!c.isSingleDoc())return Promise.resolve(!1);a=c.getSingleDoc();if(!a.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var d=T(a,"viewer");return d.hasCapability("errorReporter")?d.isTrustedViewer().then(function(a){if(!a)return!1;d.sendMessage("error",F({m:b.m,a:b.a,s:b.s,el:b.el,ex:b.ex,v:b.v,jse:b.jse}));return!0}):Promise.resolve(!1)}
function lc(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var k=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var h=!(self&&self.window),n=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||h)if(k=!0,.001<n)return;var m=0<=a.indexOf("\u200b\u200b\u200b");if(!(m&&.1<n)){g=Object.create(null);g.v=u().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=m?"1":"0";g.ex=k?"1":"0";g.dw=h?"1":"0";var p="1p";self.context&&
self.context.location?(g["3p"]="1",p="3p"):u().runtime&&(p=u().runtime);u().singlePassType&&(g.spt=u().singlePassType);g.rt=p;"inabox"===p&&(g.adid=u().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var hb=
self.AMP.viewer.getResolvedViewerUrl(),G=self.AMP.viewer.maybeGetMessagingOrigin();hb&&(g.rvu=hb);G&&(g.mso=G)}ic||(ic=oc());g.jse=ic;var t=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var r in f)t.push(r+"="+(f[r]?"1":"0"));g.exps=t.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),m||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document?self.document.referrer:"";
g.ae=X.join(",");g.fr=self.location.originalHash||self.location.hash;b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return g}}}function kc(){var a=self;if(!a.document)return!1;a=a.document.querySelectorAll("script[src]");for(var b=0;b<a.length;b++)if(!M(a[b].src.toLowerCase()))return!0;return!1}
function oc(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(J(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(J(b,"Error: message"))return"Chrome"}return"unknown"};function pc(a,b,c){var d=self.location;Ga(c);var e=M(d),f=L(Ea(d));if("href"==b&&!J(c,"#"))return Fa(c,f);if("src"==b)return"amp-img"==a?qc(c,f,e):Fa(c,f);if("srcset"==b){try{var g=Db(c)}catch(k){return A().error("URL-REWRITE","Failed to parse srcset: ",k),c}return g.stringify(function(a){return qc(a,f,e)})}return c}
function qc(a,b,c){a=L(Fa(a,b));return"data:"==a.protocol||M(a)||!c?a.href:y.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};function rc(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function sc(a,b){var c=rc,d=c(a);if(d)b(a);else{var e=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",e))};a.addEventListener("readystatechange",e)}}function tc(a){return new Promise(function(b){sc(a,b)})};var uc=/^(i?-)?amp(html)?-/,vc={INPUT:{checked:!0,value:!0},OPTION:{selected:!0},TEXTAREA:{text:!0}},wc=E({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state","is-layout-container"],"AMP-SELECTOR":["selected"]}),xc=["AMP-LIST"];
function yc(a,b){var c=this;this.ampdoc=a;this.h=a.win;this.H=b||a.win;this.X=[];this.Aa=$b(this.h,function(){c.X.length=0});this.G=[];this.C=E();this.Z=T(a,"history");this.ma=[];this.I=1E3;this.ka=T(a,"mutator");this.w=E();this.Da=S(this.h,"timer");this.qa=null;this.V=T(this.ampdoc,"viewer");this.V.onMessageRespond("premutate",this.Ba.bind(this));this.na=a.whenFirstVisible().then(function(){if(b){var c=b.document;return tc(c).then(function(){return c})}return a.whenReady().then(function(){return a.getRootNode()})});
this.L=this.na.then(function(a){return zc(c,a)});this.da=new K;this.U=null;this.oa=new Zb;var d=self.AMP;d.printState=d.printState||this.ya.bind(this);d.setState=d.setState||function(a){return c.setState(a)};d.eval=d.eval||this.xa.bind(this)}yc.installInEmbedWindow=function(a,b){Pa(a,new yc(b,a))};l=yc.prototype;l.signals=function(){return this.oa};
l.setState=function(a,b){var c=this;b=void 0===b?{}:b;B().info("amp-bind","setState (init=%s):",b.skipEval,a);try{pa(this.w,a)}catch(d){A().error("amp-bind","Failed to merge result from AMP.setState().",d)}return b.skipEval?Promise.resolve():this.U=this.L.then(function(){return Ac(c)}).then(function(a){return Bc(c,a,{skipAmpState:b.skipAmpState,constrain:b.constrain})})};
l.invoke=function(a){var b=a,c=b.args,d=b.event,e=b.method,f=b.sequenceId,g=b.tagOrTarget;if(this.X.includes(f))return A().error("amp-bind","One state action allowed per event."),Promise.resolve();this.X.push(f);this.Aa();if(b=c.__AMP_OBJECT_STRING__)switch(this.I=Math.min(2E3,Math.max(1E3,this.I+500)),this.oa.signal("FIRST_MUTATE"),c={},d&&d.detail&&(c.event=d.detail),e){case "setState":return this.setStateWithExpression(b,c);case "pushState":return this.pushStateWithExpression(b,c);default:return Promise.reject(B().createError("Unrecognized method: %s.%s",
g,e))}else A().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return Promise.resolve()};l.setStateWithExpression=function(a,b){var c=this;return Cc(this,a,b).then(function(a){return Dc(c,a)})};l.setStateWithObject=function(a){return(a=Ec(a))?Dc(this,a):Promise.reject("Invalid state")};
function Dc(a,b){B().info("amp-bind","setState:",b);a.U=a.setState(b).then(function(){return Fc(a)}).then(function(b){b&&a.Z.replace(b)});return a.U}l.pushStateWithExpression=function(a,b){var c=this;B().info("amp-bind","pushState:",a);return Cc(this,a,b).then(function(a){function b(){return c.setState(d)}var d=E();Object.keys(a).forEach(function(a){d[a]=Ec(c.w[a])});return c.setState(a).then(function(){return Fc(c)}).then(function(a){c.Z.push(b,a)})})};
function Fc(a){var b=F({data:F({"amp-bind":a.w}),title:a.H.document.title});return a.V.isEmbedded()?a.V.isTrustedViewer().then(function(a){return a?b:null}):Promise.resolve(b)}l.rescan=function(a,b,c){var d=this;c=void 0===c?{}:c;var e=c.fast?this.da.promise:this.L;return e.then(function(){return d.Da.timeoutPromise(c.timeout||2E3,Gc(d,a,b,c),"Timed out waiting for amp-bind to rescan.")})};
function Gc(a,b,c,d){B().info("amp-bind","rescan: ",b,c,d);var e=d.fast?Hc(a,b,c):Ic(a,b,c);return e.then(function(){if(d.update)return Ac(a).then(function(c){return Bc(a,c,{constrain:b})})})}
function Hc(a,b,c){var d=Jc(a,c),e=[],f=b.filter(function(a){return a.hasAttribute("i-amphtml-binding")});b.forEach(function(a){a=a.querySelectorAll("[i-amphtml-binding]");Array.prototype.push.apply(f,a)});var g=a.I-a.numberOfBindings();for(b=0;b<f.length&&!Kc(a,f[b],g-e.length,e);b++);d.then(function(b){B().info("amp-bind","rescan.fast: delta=%s, total=%s",e.length-b,a.numberOfBindings())});return 0<e.length?Lc(a,e):Promise.resolve()}
l.getState=function(a){a=a?kb(this.w,a):void 0;return w(a)||Array.isArray(a)?Ec(a):a};l.getStateAsync=function(a){var b=this,c=/^[^.]*/.exec(a)[0];return this.na.then(function(d){var e=d.querySelector("#"+String(c).replace(Wa,Xa));if(!e)throw Error("#"+c+" does not exist.");return eb(e).then(function(a){return a.getImpl(!0)}).then(function(a){return a.getFetchingPromise()}).catch(function(){}).then(function(){return b.getState(a)})})};
l.getStateValue=function(a){a=kb(this.w,a);return void 0===a||null===a?null:w(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
function zc(a,b){var c=!dc(a.H.document);a.qa=new Lb(c);return Z(a,"bind.init",[c]).then(function(){return Promise.all([Mc(a).then(function(){return a.da.resolve()}),Nc(a,[b])])}).then(function(){b.addEventListener("amp:dom-update",function(b){return Oc(a,b)})}).then(function(){var a=b.querySelectorAll("AMP-STATE"),c=!1,f=v(a).map(function(a){return eb(a).then(function(){return a.getImpl(c)}).then(function(a){return a.parseAndUpdate()})});return Promise.all(f)}).then(function(){a.V.sendMessage("bindReady",
void 0);if(u().development)return Ac(a).then(function(b){return Pc(a,b)})})}l.numberOfBindings=function(){return this.G.reduce(function(a,b){return a+b.boundProperties.length},0)};l.Ia=function(a){this.I=a};l.Ga=function(){return this.Z};
l.Ba=function(a){var b=this,c=[];return this.L.then(function(){Object.keys(a.state).forEach(function(d){b.ma.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&A().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};l.addOverridableKey=function(a){this.ma.push(a)};
function Mc(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];cb(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Z(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){Qc(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function Nc(a,b){if(!b.length)return Promise.resolve(0);var c=b.map(function(b){var c=a.I-a.numberOfBindings();return Rc(a,b,c).then(function(b){var c=b.bindings,d=b.limitExceeded;d&&B().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.I);return c})});return Promise.all(c).then(function(b){b=Array.prototype.concat.apply([],b);return 0<b.length?Lc(a,b):0})}
function Lc(a,b){return Z(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(b){var d=a.C[b];0<d.length&&Qc(c[b],'amp-bind: Expression compile error in "'+b+'".',d[0])});return b.length})}
function Jc(a,b){if(!b.length)return Promise.resolve(0);qb(a.G,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!0;return!1});var c=[],d;for(d in a.C){var e=a.C[d];qb(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!0;return!1});0==e.length&&(c.push(d),delete a.C[d])}var f=c.length;return 0<f?Z(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function Rc(a,b,c){function d(){var b=f.currentNode;if(!b)return!0;if(b.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();var d=c-e.length;Kc(a,b,d,e)&&(g=!0);if(xc.includes(b.nodeName))a:{b=f;for(var n=b.currentNode;n;n=b.parentNode())if(n=b.nextSibling()){b=n;break a}b=null}else b=f.nextNode();var m=b;return!m||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(b){function c(f){var h=!1;if(f&&!f.didTimeout)for(;1<
f.timeRemaining()&&!h;)h=d();else{var k=250;for(f=0;f<k&&!h;f++)h=d()}h?b({bindings:e,limitExceeded:g}):Rb(a.ampdoc,c)}Rb(a.ampdoc,c)})}function Kc(a,b,c,d){var e=!1,f=Sc(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.G.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(c){var e=c,f=e.expressionString;d.push({tagName:g,property:e.property,expressionString:f});a.C[f]||(a.C[f]=[]);a.C[f].push(b)});return e}
function Sc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){a:{var g=void 0,k=a,h=d[e];var n=b;var m=n.tagName,p=h.name;if(2<p.length&&"["===p[0]&&"]"===p[p.length-1])g=p.substr(1,p.length-2);else if(J(p,"data-amp-bind-")&&(g=p.substr(14),n.hasAttribute("["+g+"]"))){n=null;break a}if(g){if(k.qa.canBind(m,g)){n={property:g,expressionString:h.value};break a}g=A().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",g,m);Y(g,n)}n=null}n&&c.push(n)}return c}
function Cc(a,b,c){return a.L.then(function(){Object.assign(c,a.w);return Z(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw Qc(a,"amp-bind: Expression eval failed.");return b})}
function Ac(a){var b=Z(a,"bind.evaluateBindings",[a.w]);return b.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.C[b];if(0<c.length){var d=e[b],f=A().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",b,d.message);f.stack=d.stack;Y(f,c[0])}});B().info("amp-bind","evaluation:",c);return c})}
function Pc(a,b){var c=void 0===c?null:c;var d=void 0===d?!0:d;var e={};a.G.forEach(function(a){var f=a.element;a=a.boundProperties;c&&!Tc(c,f)||a.forEach(function(a){var c=b[a.expressionString];if(void 0!==c){var g=a.property,m=wc[f.tagName];if(m&&m.includes(g))c=null;else{switch(g){case "text":g=f.textContent;c=String(c);m=g.trim()===c.trim();break;case "class":g=[];for(m=0;m<f.classList.length;m++){var p=f.classList[m];uc.test(p)||g.push(p)}p=[];Array.isArray(c)?p=c:"string"===typeof c?(m=c.trim(),
0<m.length&&(p=m.split(" "))):(m=A().createError('%s: "%s" is not a valid result for [class].',"amp-bind",c),Y(m,f));b:{m=g;var k=p;if(m.length!==k.length)m=!1;else{p=(Array.isArray(m)?m:v(m)).sort();k=(Array.isArray(k)?k:v(k)).sort();for(var G=0;G<m.length;G++)if(p[G]!==k[G]){m=!1;break b}m=!0}}break;default:g=f.getAttribute(g),m=!0===c?""===g:!1===c?null===g:"number"===typeof c?Number(g)===c:g===c}c=m?null:{expected:c,actual:g}}var t=c;if(t){c=f.tagName;g=a.property;a=a.expressionString;m=t;p=m.expected;
var r=m.actual;e[c+"["+g+"]"+p+":"+r]=!0;d&&A().warn("amp-bind","Default value ("+r+") does not match first result ("+(p+") for <"+c+" ["+g+']="')+(a+'">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.'))}}})});return Object.keys(e)}function Tc(a,b){for(var c=0;c<a.length;c++)if(a[c].contains(b))return!0;return!1}
function Uc(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||mb(f,d)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}function Bc(a,b,c){var d=[];a.G.forEach(function(e){c.skipAmpState&&"AMP-STATE"===e.element.tagName||(!c.constrain||c.constrain.some(function(a){return a.contains(e.element)}))&&d.push(Vc(a,b,e))});return Promise.all(d)}
function Vc(a,b,c){var d=c.element,e=Uc(c.boundProperties,b);return 0===e.length?Promise.resolve():a.ka.mutateElement(d,function(){var b=E(),c,k;e.forEach(function(e){var f=e,g=f.boundProperty,h=f.newValue;f=g.property;a:{g=g.property;var n=d.tagName;switch(g){case "defaulttext":d.textContent=String(h);break;case "text":g=String(h);"TITLE"===n&&d.parentNode===a.H.document.head&&(a.H.document.title=g);"TEXTAREA"===n?d.value=g:d.textContent=g;break;case "class":g=[];for(var t=0;t<d.classList.length;t++){var r=
d.classList[t];uc.test(r)&&g.push(r)}Array.isArray(h)||"string"===typeof h?d.setAttribute("class",g.concat(h).join(" ")):null===h?d.setAttribute("class",g.join(" ")):(g=A().createError('%s: "%s" is not a valid result for [class].',"amp-bind",h),Y(g,d));break;default:var tb="INPUT"===n&&g in d,H=d.getAttribute(g);n=!1;if("boolean"===typeof h){if(tb&&d[g]!==h&&(d[g]=h,n=!0),h&&""!==H?(d.setAttribute(g,""),n=!0):h||null===H||(d.removeAttribute(g),n=!0),n&&"OPTION"===d.tagName&&"selected"===g&&h&&S(a.h,
"platform").isSafari()&&(t=bb(d,"select")))r=v(t.options).indexOf(d),0<=r&&(t.selectedIndex=r)}else if("object"===typeof h&&null!==h)n=!0;else if(h!==H)b:{H=String(h);try{t=d.tagName.toLowerCase();r=g.toLowerCase();var Ha="src"==r||"href"==r||"xlink:href"==r||"srcset"==r?pc(t,r,H):H;if(M(self.location)&&"a"===t&&"href"===r){var ub=d.getAttribute(r),vb="#"===Ha[0],wb=ub&&"#"===ub[0];vb&&!wb?(d.__AMP_ORIGINAL_TARGET_VALUE_||(d.__AMP_ORIGINAL_TARGET_VALUE_=d.getAttribute("target")),d.removeAttribute("target")):
wb&&!vb&&d.setAttribute("target",d.__AMP_ORIGINAL_TARGET_VALUE_||"_top")}tb&&(d[r]=Ha);d.setAttribute(r,Ha);n=!0;break b}catch(Wc){t=A().createError('%s: "%s" is not a valid result for [%]',"amp-bind",H,g,Wc),Y(t,d)}n=!1}if(n){g={name:g,value:h};break a}}g=null}var Ia=g;Ia&&(b[Ia.name]=Ia.value,"width"==f?c="number"===typeof h&&isFinite(h)?Number(h):c:"height"==f&&(k="number"===typeof h&&isFinite(h)?Number(h):k));(h=vc[d.tagName])&&h[f]&&(f="OPTION"===d.tagName?bb(d,"SELECT"):d)&&(h=pb(a.H,"amp:form-value-change",
null,{bubbles:!0}),f.dispatchEvent(h))});void 0===c&&void 0===k||a.ka.forceChangeSize(d,k,c);if("function"===typeof d.mutatedAttributesCallback)try{d.mutatedAttributesCallback(b)}catch(n){var h=A().createError("%s: Applying expression results (%s) failed with error,","amp-bind",JSON.stringify(b),n);Y(h,d)}})}function Oc(a,b){b=b.target;var c=b.parentNode;c&&xc.includes(c.nodeName)||(B().info("amp-bind","dom_update:",b),Ic(a,[b],[b],"dom_update.end").then(function(){}))}
function Ic(a,b,c,d){d=void 0===d?"rescan.slow":d;var e=0;return Jc(a,c).then(function(c){e=c;return Nc(a,b)}).then(function(b){B().info("amp-bind","%s: delta=%s, total=%s",d,b-e,a.numberOfBindings())})}function Z(a,b,c){var d=a.h;a=a.H;if(d.Worker){var e=O(d);Qa(e,e,"amp-worker",bc);d=S(d,"amp-worker");b=cc(d,b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function Qc(a,b,c){b=A().createError("%s %s",b,a.message);b.stack=a.stack;Y(b,c);return b}
function Ec(a){if(void 0===a)return null;try{return JSON.parse(JSON.stringify(a))}catch(b){B().error("amp-bind","Failed to copy JSON ("+a+") with error: "+b)}return null}
l.ya=function(a){if(a)if("string"==typeof a){var b=kb(this.w,a);A().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=A().assertElement(a),Xc(this,b)):A().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else A().info("amp-bind",this.w)};
function Xc(a,b){var c=rb(a.G,function(a){return a.element==b});if(0>c)A().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.G[c].boundProperties;e.forEach(function(b){d.push(Cc(a,b.expressionString,a.w))});Promise.all(d).then(function(a){var b=E();e.forEach(function(c,d){b[c.property]=a[d]});A().info("amp-bind",b)})}}l.xa=function(a){Cc(this,a,this.w).then(function(a){A().info("amp-bind",a)})};l.Ha=function(){return this.L};l.Ja=function(){return this.U};(function(a){a.registerServiceForDoc("bind",yc);a.registerElement("amp-state",xb);a.registerElement("amp-bind-macro",ta)})(self.AMP);
})});

//# sourceMappingURL=amp-bind-0.1.js.map
